### PR TITLE
Fix a bug causing atob to work incorrectly for some inputs

### LINKED ISSUE #13: atob isn't entirely correct
The following function:

```javascript
atob("AacABdxfoCQ=").length
```

returns 8 in the browser (which is correct), but just 6 in jsaas (which is not correct).

To test:

1. Create a file named `/tmp/b.js` and populate it with:

```javascript
function() {
    return atob("AacABdxfoCQ=").length;
}
```

2. Execute the program:

```
curl -v -d'@/tmp/b.js' http://localhost:9880/execute
```

The length will be returned as the result.

### PR DESCRIPTION
**Pull request by longshorej**
This appears to have to do with how Duktape was interpreting strings, I suspect something related to its internal CESU-8 encoding.

As a workaround, we lean on String.fromCharCode to create a string from the raw buffer data.

Fixes #13

### CODE REVIEW

**Comment by longshorej** [comment]
Good question - reasonably confident -- the `CString`s are freed on L79/L80. Everything else is managed by Duktape. I'll stress it in a bit to be sure though.

**Comment by longshorej** [comment]
Yeah, I can't reproduce any memory leaks. If I comment out L79/L80, I can reproduce memory leaks (as expected).

I pushed an update to comment on the memory safety and be more explicit.

Here's some additional thoughts:

* Duktape uses `setjmp`/`longjmp` as the mechanism for its errors. Thus, if this mechanism is exercised, Rust's ownership system will not be able to free any memory.
* In this code, `duk_require_string`, `duk_base64_decode`, `duk_get_global_string`, `duk_get_prop_string`, `duk_dup` can exercise this mechanism i.e. they can fail.
* This code's allocates two `CString`s.
* `duk_require_string` and `duk_base64_decode` are called before the allocations are performed, so there isn't anything to free.
* Since I have moved the `CString` freeing lines to immediately after the calls to `duk_get_global_string` and `duk_get_prop_string`, thus there is no need to worry about calls afterwards failing (notably, `duk_dup`, `duk_push_uint`).
* Given that the context is always identical, we can reason that the calls to `duk_get_global_string`, `duk_get_prop_string` cannot fail. Therefore, I think it's reasonable to conclude the two allocated `CString`s are always freed.

**Comment by huntc** [comment]
Thanks for the comprehensive follow up!

**Comment by huntc** [comment]
A further thought: should we have just implemented our own base64 codec? I wouldn’t think that’d be hard.

**Comment by longshorej** [comment]
In this case, it wouldn't have changed anything -- this was purely about converting a byte buffer into a JS string without losing input. Had we used the base64 crate, we'd still have the same challenge.

**Comment by huntc** [comment]
Thanks for info. I suspected as much.

**Pull request merged**
